apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-canary-deployment
spec:
 selector:
  matchLabels:
   app: nginx
 replicas: 1
 template:
  metadata:
   labels:
    app: nginx
    version: "2.0"
  spec:
   containers:
    - name: nginx
      image: nginx:latest
      resources:
       limits:
        memory: "128Mi"
        cpu: "50m"
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginx-conf
        mountPath: /usr/share/nginx/html/
   volumes:
    - name: nginx-conf
      hostPath:
        path: /home/nathan/projet_kubernetes/kubernetes-canary/2
